name: 'Test'
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: workflow/nix-shell-action@v3
        with:
          flakes: | 
            .#build
          script: |
            # Runs hello from a local flake.nix
            build
